### ISSUE TITLE
Project Loading Failed

### ISSUE THREAD

**Issue by rajeshkrmeena** [ucb-bar/fpga-zynq#112]
Trying  "Building Everything from Scratch"  but failed to create Vivado project :

I run the command " make project " in Zybo directory. When run first time, it took some time and stuck at following

...
...
...
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at sbt.JLine$$anonfun$createReader$1.apply(LineReader.scala:103)
	at sbt.JLine$$anonfun$createReader$1.apply(LineReader.scala:102)
	at sbt.JLine$$anonfun$usingTerminal$1.apply(LineReader.scala:98)
	at sbt.JLine$$anonfun$usingTerminal$1.apply(LineReader.scala:96)
	at sbt.JLine$.withTerminal(LineReader.scala:89)
	at sbt.JLine$.usingTerminal(LineReader.scala:96)
	at sbt.JLine$.createReader(LineReader.scala:102)
	at sbt.SimpleReader.<init>(LineReader.scala:139)
	at sbt.SimpleReader$.<init>(LineReader.scala:141)
	at sbt.SimpleReader$.<clinit>(LineReader.scala)
	at sbt.BuiltinCommands$.sbt$BuiltinCommands$$doLoadFailed(Main.scala:510)
	at sbt.BuiltinCommands$$anonfun$loadFailed$1.apply(Main.scala:502)
	at sbt.BuiltinCommands$$anonfun$loadFailed$1.apply(Main.scala:502)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

Note : updated sbt and scala on an ubuntu system.

**Comment by rajeshkrmeena** [comment]
Update : Issue resolved after changing the Java Version from "default-jre" to  "openjdk-8-jre-headless"
