### ISSUE TITLE
Make rocket error: unresolved dependencies

### ISSUE THREAD

**Issue by FxPiGaAo** [ucb-bar/fpga-zynq#90]
I was following the steps on README and when I came to the Pushing Your Rocket Modifications to the FPGA part, I encountered this problem running : make rocket.

xhc@xhcPC:~/test/fpga-zynq/zedboard$ make rocket
cd /home/xhc/test/fpga-zynq/rocket-chip && java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /home/xhc/test/fpga-zynq/rocket-chip/sbt-launch.jar pack
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/xhc/test/fpga-zynq/rocket-chip/project
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
Using addons: 
[info] Set current project to rocketchip (in build file:/home/xhc/test/fpga-zynq/rocket-chip/)
[info] Updating coreMacros...
[info] Done updating.
[info] Updating chiselFrontend...
[info] Done updating.
[info] Compiling 4 Scala sources to /home/xhc/test/fpga-zynq/rocket-chip/chisel3/coreMacros/target/scala-2.11/classes ...
[info] Done compiling.
[info] Updating chisel...
[info] Done updating.
[info] Packaging /home/xhc/test/fpga-zynq/rocket-chip/chisel3/coreMacros/target/scala-2.11/coremacros_2.11-3.2-SNAPSHOT.jar ...
[info] Done packaging.
[info] Updating hardfloat...
[info] Done updating.
[info] Compiling 12 Scala sources to /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/target/scala-2.11/classes ...
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala:81:24: method flatten in class Data is deprecated: pending removal once all instances replaced
[warn]     SeqUtils.do_asUInt(flatten.map(_.asUInt()))
[warn]                        ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala:87:15: method flatten in class Data is deprecated: pending removal once all instances replaced
[warn]     for (x <- flatten) {
[warn]               ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Annotation.scala:47:30: method apply in object Annotation is deprecated: This returns a LegacyAnnotation, use an explicit Annotation type
[warn]   def toFirrtl: Annotation = Annotation(component.toNamed, transformClass, value)
[warn]                              ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Assert.scala:41:57: method lineContent in trait Position is deprecated: removed from the public API
[warn]     val condStr = s"${p.source.file.name}:${p.line} ${p.lineContent.trim}"
[warn]                                                         ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Assert.scala:49:57: method lineContent in trait Position is deprecated: removed from the public API
[warn]     val condStr = s"${p.source.file.name}:${p.line} ${p.lineContent.trim}"
[warn]                                                         ^
[warn] 5 warnings found
[info] Done compiling.
[info] Compiling 28 Scala sources to /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/target/scala-2.11/classes ...
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala:81:24: method flatten in class Data is deprecated: pending removal once all instances replaced
[warn]     SeqUtils.do_asUInt(flatten.map(_.asUInt()))
[warn]                        ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Aggregate.scala:87:15: method flatten in class Data is deprecated: pending removal once all instances replaced
[warn]     for (x <- flatten) {
[warn]               ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Annotation.scala:47:30: method apply in object Annotation is deprecated: This returns a LegacyAnnotation, use an explicit Annotation type
[warn]   def toFirrtl: Annotation = Annotation(component.toNamed, transformClass, value)
[warn]                              ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Assert.scala:41:57: method lineContent in trait Position is deprecated: removed from the public API
[warn]     val condStr = s"${p.source.file.name}:${p.line} ${p.lineContent.trim}"
[warn]                                                         ^
[warn] /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/src/main/scala/chisel3/core/Assert.scala:49:57: method lineContent in trait Position is deprecated: removed from the public API
[warn]     val condStr = s"${p.source.file.name}:${p.line} ${p.lineContent.trim}"
[warn]                                                         ^
[warn] 5 warnings found
[info] Done compiling.
[info] Updating ...
[warn] 	module not found: edu.berkeley.cs#chisel3_2.12;3.2-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/xhc/.ivy2/local/edu.berkeley.cs/chisel3_2.12/3.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/berkeley/cs/chisel3_2.12/3.2-SNAPSHOT/chisel3_2.12-3.2-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/xhc/.sbt/preloaded/edu.berkeley.cs/chisel3_2.12/3.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/xhc/.sbt/preloaded/edu/berkeley/cs/chisel3_2.12/3.2-SNAPSHOT/chisel3_2.12-3.2-SNAPSHOT.pom
[warn] 	module not found: edu.berkeley.cs#hardfloat_2.12;1.2
[warn] ==== local: tried
[warn]   /home/xhc/.ivy2/local/edu.berkeley.cs/hardfloat_2.12/1.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/edu/berkeley/cs/hardfloat_2.12/1.2/hardfloat_2.12-1.2.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/xhc/.sbt/preloaded/edu.berkeley.cs/hardfloat_2.12/1.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/xhc/.sbt/preloaded/edu/berkeley/cs/hardfloat_2.12/1.2/hardfloat_2.12-1.2.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: edu.berkeley.cs#chisel3_2.12;3.2-SNAPSHOT: not found
[warn] 	:: edu.berkeley.cs#hardfloat_2.12;1.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		edu.berkeley.cs:chisel3_2.12:3.2-SNAPSHOT
[warn] 		  +- berkeley:rocketchip_2.12:1.2
[warn] 		edu.berkeley.cs:hardfloat_2.12:1.2
[warn] 		  +- berkeley:rocketchip_2.12:1.2
[info] Packaging /home/xhc/test/fpga-zynq/rocket-chip/chisel3/chiselFrontend/target/scala-2.11/chiselfrontend_2.11-3.2-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 29 Scala sources to /home/xhc/test/fpga-zynq/rocket-chip/chisel3/target/scala-2.11/classes ...
[info] Done compiling.
[info] Packaging /home/xhc/test/fpga-zynq/rocket-chip/chisel3/target/scala-2.11/chisel3_2.11-3.2-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 27 Scala sources to /home/xhc/test/fpga-zynq/rocket-chip/hardfloat/target/scala-2.11/classes ...
[warn] there were 867 feature warnings; re-run with -feature for details
[warn] one warning found
[info] Done compiling.
[info] Packaging /home/xhc/test/fpga-zynq/rocket-chip/hardfloat/target/scala-2.11/hardfloat_2.11-1.2.jar ...
[info] Done packaging.
[error] sbt.librarymanagement.ResolveException: unresolved dependency: edu.berkeley.cs#chisel3_2.12;3.2-SNAPSHOT: not found
[error] unresolved dependency: edu.berkeley.cs#hardfloat_2.12;1.2: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: edu.berkeley.cs#chisel3_2.12;3.2-SNAPSHOT: not found
[error] unresolved dependency: edu.berkeley.cs#hardfloat_2.12;1.2: not found
[error] Total time: 28 s, completed 18-Jul-2018 2:55:18 PM
../common/Makefrag:80: recipe for target '/home/xhc/test/fpga-zynq/common/lib/rocketchip.stamp' failed
make: *** [/home/xhc/test/fpga-zynq/common/lib/rocketchip.stamp] Error 1

I have already run the command in the chisel3 repository: 

> sbt publishLocal 

But it seems that there are still unresolved dependencies. Now I don't know how to deal with this problem.

**Comment by FxPiGaAo** [comment]
This issue is solved by myself. I forgot to initiate the submodules...
Could you please modify the README file to clarify where to run the command:
make init-submodules
Newbies like me have to learn the make command rules to understand where to run the command. Although it's a good chance for newbies to learn a lot of basic things, I think a clear document is more helpful.
